// <auto-generated />
namespace MyNote.Api.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class modify_audit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(modify_audit));
        
        string IMigrationMetadata.Id
        {
            get { return "201801071246211_modify_audit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
